# Generated by Django 5.1.6 on 2025-03-06 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salário'), ('Food', 'Alimentação'), ('Rent', 'Moradia'), ('Transport', 'Transporte'), ('Other', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Receita'), ('Receita', 'Receita'), ('Loss', 'Despesa'), ('Despesa', 'Despesa')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['income', 'receita', 'expense', 'despesa'])), name='check_transaction_type'),
        ),
    ]
