# Generated by Django 5.1.6 on 2025-03-06 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_category_alter_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='check_transaction_type',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['Income', 'Receita', 'Loss', 'Despesa'])), name='check_transaction_type'),
        ),
    ]
